-- MySQL Script generated by MySQL Workbench
-- mar. 19 juil. 2022 15:55:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CORSAIR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CORSAIR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CORSAIR` ;
USE `CORSAIR` ;

-- -----------------------------------------------------
-- Table `CORSAIR`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CORSAIR`.`City` (
  `CityName` VARCHAR(90) NOT NULL,
  `City` INT NOT NULL,
  `Cityplace_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`City`));


-- -----------------------------------------------------
-- Table `CORSAIR`.`Coworkingplaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CORSAIR`.`Coworkingplaces` (
  `ID` INT NOT NULL,
  `Nameplace` VARCHAR(90) NOT NULL,
  `Cityplace` VARCHAR(45) NOT NULL,
  `Feedback` VARCHAR(45) NOT NULL,
  `Openhours` VARCHAR(45) NOT NULL,
  `Services` VARCHAR(45) NOT NULL,
  `City_City` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Coworkingplaces_City_idx` (`City_City` ASC) VISIBLE,
  CONSTRAINT `fk_Coworkingplaces_City`
    FOREIGN KEY (`City_City`)
    REFERENCES `CORSAIR`.`City` (`City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
