-- MySQL Script generated by MySQL Workbench
-- mar. 19 juil. 2022 23:10:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corsair
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corsair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corsair` ;
USE `corsair` ;

-- -----------------------------------------------------
-- Table `corsair`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corsair`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cityplace` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

insert into city (cityplace) values ('Paris');
insert into city (cityplace) values ('Marseille');
insert into city (cityplace) values ('Nantes');




-- -----------------------------------------------------
-- Table `corsair`.`coworkingplaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corsair`.`coworkingplaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `hoursopen` VARCHAR(255) NOT NULL,
  `feedback` VARCHAR(255) NOT NULL,
  `services` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coworkingplaces_city_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_coworkingplaces_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `corsair`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

insert into coworkingplaces (`name`, `hoursopen`, `feedback`, `services`, `city_id`) values ('Startway Coworking Paris Sentier', 'De 9h00 à 18h00 !', 'Très bon endroit de coworking, 95% de notes positives.', 'Nous proposons un endroit détente, une salle de réunion et une salle de sport !', 1);
insert into coworkingplaces (`name`, `hoursopen`, `feedback`, `services`, `city_id`) values ('MOZAIK Coworking Spaces Chaussée Antin', 'De 8h00 à 17h30 !', 'Joli endroit de coworking, 90% de notes positives.', 'Salle de sport, SPA et même des macbooks !', 2);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
