-- MySQL Script generated by MySQL Workbench
-- mar. 19 juil. 2022 23:10:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corsair
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corsair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corsair` ;
USE `corsair` ;

-- -----------------------------------------------------
-- Table `corsair`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corsair`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cityplace` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `corsair`.`coworkingplaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corsair`.`coworkingplaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `hoursopen` VARCHAR(45) NOT NULL,
  `feedback` VARCHAR(255) NOT NULL,
  `services` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coworkingplaces_city_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_coworkingplaces_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `corsair`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
